### ISSUE TITLE
receive_message method should be update

### ISSUE THREAD

**Issue by repair77** [MsLolita/grass#78]
i received this message ,how should I do?

{'id':'LlYiuUsq6xjgWhGekI4nz'，'action'	
: 'HTTP_REQUEST', 'data': {'url': 'http://WsServ-wsser-2YTAKtveCtaD-200e534a774d479a.elb.us-east-1.amazonaws.com/e65c798e44045cf3241e5bdc52aff12c/jWctVOSuTcPjwTgY', 'method': 'GET', 'headers':{'Accept': '*/*', Host': 'wsserv-wsser-2ytaktvectad-200e534a774d479a.elb.us-east-1.amazonaws.com','User-Agent':"wynd.netwo rk/3.0.1'}，'authenticated':False}}

**Comment by milkthecow-moo** [comment]
The newest update to grass added HTTP requests. Theoretically these request can happen at any time though I have observed that this is only sent ONCE and that is after the first pong sent when a connection is established. The http request does not appear to be sent again after that(unless you disconnect and reconnect) but theoretically it can be sent at any time. I'll try making a pull request whenever I get some extra time(if its not already fixed by then)

**Comment by MsLolita** [comment]
added
